### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by SafwatHalaby** [TheWanderer/stiler#4]
This error occurs regardless of the parameters I give.

```
>python stiler.py left
   Traceback (most recent call last):
   File "stiler.py", line 102, in <module>  
   (Desktop,OrigXstr,OrigYstr,MaxWidthStr,MaxHeightStr,WinList) = initialize()
   File "stiler.py", line 52, in initialize
   current =  filter(lambda x: x.split()[1] == "*" , desk_output)[0].split()
   IndexError: list index out of range
```

**Comment by krsna-rand** [comment]
Verify that you have `wmctrl` installed.

`File "stiler.py", line 52, in initialize`
`def initialize():`
   ` desk_output = commands.getoutput("`**wmctrl** `-d").split("\n")`
